<a href="https://colab.research.google.com/github/Jashwanth-rit/Machine-learning---Hands-on/blob/main/Deep_learning_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2


4

In [5]:
import torch
import numpy as np


In [3]:
tensor_2d =  torch.randn(3,4)
tensor_2d

tensor([[-0.7265, -0.5975, -0.4915,  0.9811],
        [-0.2670,  0.9754,  0.5083, -0.8347],
        [-0.6343, -0.6600, -0.3614,  1.3351]])

Basically , after importing torch just apply all the function of numpy to torch ,
other thing is tensor is one step farward of numpy , we can manipulate arrays effectively than the numpy ,

 so the cunclusion is Arraylist > Numpy > Tensor .

In [4]:
tensor_3d =  torch.randn(2,3,4)
tensor_3d

tensor([[[-0.7632, -0.6061,  0.4601, -1.4232],
         [ 0.5530, -0.7686,  0.7916,  0.3047],
         [ 0.9000,  0.0254, -0.5892,  0.3770]],

        [[ 0.5969, -1.3685, -1.4988,  1.8397],
         [ 1.3459, -0.7205, -0.0276, -1.8734],
         [ 0.4746,  0.3002,  0.0289, -1.0282]]])

In [9]:
np1 = np.random.rand(3,4)
np1

tensor_d =  torch.tensor(np1)
tensor_d

tensor([[0.3365, 0.1560, 0.5804, 0.2658],
        [0.5667, 0.2564, 0.7045, 0.6131],
        [0.7158, 0.0594, 0.7649, 0.4315]], dtype=torch.float64)

In [10]:
# operations on tensor

tensor_1 = tensor_d.reshape(12)
tensor_1

tensor([0.3365, 0.1560, 0.5804, 0.2658, 0.5667, 0.2564, 0.7045, 0.6131, 0.7158,
        0.0594, 0.7649, 0.4315], dtype=torch.float64)

In [11]:
tensor_2 = tensor_1.view(3,4)
tensor_2

tensor([[0.3365, 0.1560, 0.5804, 0.2658],
        [0.5667, 0.2564, 0.7045, 0.6131],
        [0.7158, 0.0594, 0.7649, 0.4315]], dtype=torch.float64)

Find the diffrence between reshape and view , check it .
I know how access the values by index , and slicing as similar as Numpy